"""Path: castor/core/models/activity_log.py

This module contains the Pydantic models for the Activity Log resource.

    - `_id`: ObjectId
    - `project_id`: String (reference to Projects Collection)
    - `timestamp`: Date
    - `content`: String
"""

from datetime import datetime
from typing import Optional
from pydantic import BaseModel

class ActivityLogBase(BaseModel):
    """Base model for the Activity Log resource.
    
    Note how _id is not included in the base model.
    This is because _id is generated by the database
    and should not be included when creating a new activity log.

    """
    project_id: Optional[str] = None
    timestamp: Optional[datetime] = None
    content: str

class ActivityLog(ActivityLogBase):
    """Model for the Activity Log resource."""
    _id: str
