"""Path: castor/core/models/check.py

This module contains the Pydantic models for the Check resource.

    - `_id`: ObjectId
    - `id`: String (e.g., "is_nmap_installed")
    - `description`: String
    - `created_by`: String (not a user in the database, this is for the YAML file version control)
    - `tags`: Array of tag IDs (reference to Tags Collection)
    - `command`: String
    - `success_criteria`:
        - `type`: String (e.g., "regex", "string", "boolean", "exit_code")
        - `value`: String
"""

from typing import Optional, List
from pydantic import BaseModel

class CheckBase(BaseModel):
    """Base model for the Check resource.
    
    Note how _id is not included in the base model.
    This is because _id is generated by the database
    and should not be included when creating a new check.

    """
    id: str
    description: Optional[str] = None
    created_by: Optional[str] = None
    tags: Optional[List[str]] = None
    command: Optional[str] = None
    success_criteria: Optional[dict] = None

class Check(CheckBase):
    """Model for the Check resource."""
    _id: str
