"""Path: castor/core/models/client.py

This module contains the Pydantic models for the Client resource.

    - `_id`: ObjectId
    - `client_name`: String
    - `client_contacts`: Array of contact Objects
        - `name`: String
        - `email`: String
        - `phone`: String
    - `client_notes`: String
    - `client_logo`: String or Binary data
    - `projects`: Array of project IDs
"""

from typing import Optional
from pydantic import BaseModel

class ClientBase(BaseModel):
    """Base model for the Client resource.
    
    Note how _id is not included in the base model.
    This is because _id is generated by the database
    and should not be included when creating a new client.

    """
    client_name: str
    client_contacts: Optional[list] = []
    client_notes: Optional[str] = ""
    client_logo: Optional[str] = None
    projects: Optional[list] = []

class Client(ClientBase):
    """Model for the Client resource."""
    _id: str
