"""Path: castor/core/models/command.py

This module contains the Pydantic models for the Command resource.

    - `_id`: ObjectId
    - `id`: String (e.g., "nmap")
    - `schema_version`: Number
    - `description`: String
    - `created_by`: String (not a user in the database, this is for the YAML file version control)
    - `checks`: Array of check documents (reference to Checks Collection)
    - `tags`: Array of tag IDs (reference to Tags Collection)
    - `args`: Array of argument documents
    - `command`: String
"""

from typing import Optional, List
from pydantic import BaseModel

class Argument(BaseModel):
    """Model for the Argument sub-document."""
    arg_name: str
    arg_description: Optional[str] = None
    arg_required: Optional[bool] = None
    arg_default: Optional[str] = None
    arg_example: Optional[str] = None
    arg_type: Optional[str] = None
    arg_choices: Optional[List[str]] = None

class CommandBase(BaseModel):
    """Base model for the Command resource.
    
    Note how _id is not included in the base model.
    This is because _id is generated by the database
    and should not be included when creating a new command.

    """
    id: str
    schema_version: Optional[float] = None
    description: Optional[str] = None
    created_by: Optional[str] = None
    checks: Optional[List[str]] = None
    tags: Optional[List[str]] = None
    args: Optional[List[Argument]] = None
    command: Optional[str] = None

class Command(CommandBase):
    """Model for the Command resource."""
    _id: str
