"""Path: castor/core/models/expense.py

This module contains the Pydantic models for the Expense resource.

    - `_id`: ObjectId
    - `project_id`: String (reference to Projects Collection)
    - `name`: String
    - `amount`: Number
    - `date`: Date
    - `notes`: String
"""

from datetime import datetime
from typing import Optional
from pydantic import BaseModel

class ExpenseBase(BaseModel):
    """Base model for the Expense resource.
    
    Note how _id is not included in the base model.
    This is because _id is generated by the database
    and should not be included when creating a new expense.

    """
    project_id: Optional[str] = None
    name: str
    amount: float
    date: Optional[datetime] = datetime.now().isoformat()
    notes: Optional[str] = None

class Expense(ExpenseBase):
    """Model for the Expense resource."""
    _id: str
