"""Path: castor/core/models/notification.py

This module contains the Pydantic models for the Notification resource.

    - `_id`: ObjectId
    - `project_id`: String (reference to Projects Collection)
    - `notification_title`: String
    - `notification_content`: String
    - `notification_timestamp`: Date
    - `notification_read`: Boolean
"""

from datetime import datetime
from typing import Optional
from pydantic import BaseModel

class NotificationBase(BaseModel):
    """Base model for the Notification resource.
    
    Note how _id is not included in the base model.
    This is because _id is generated by the database
    and should not be included when creating a new notification.

    """
    project_id: Optional[str] = None
    notification_title: str
    notification_content: str
    notification_timestamp: Optional[datetime] = None
    notification_read: Optional[bool] = None

class Notification(NotificationBase):
    """Model for the Notification resource."""
    _id: str
