"""Path: castor/core/models/client.py

This module contains the Pydantic models for the Client resource.

    - `_id`: ObjectId
    - `permission_name`: String
    - `permission_description`: String
"""

from typing import Optional
from pydantic import BaseModel

class PermissionBase(BaseModel):
    """Base model for the Permission resource.
    
    Note how _id is not included in the base model.
    This is because _id is generated by the database
    and should not be included when creating a new permission.

    """
    permission_name: str
    permission_description: str

class Permission(PermissionBase):
    """Model for the Permission resource."""
    _id: str
