"""Path: castor/core/models/preference.py

This module contains the Pydantic models for the Preference resource.

    - `_id`: ObjectId
    - `user_id`: ObjectId (reference to Users Collection)
    - `theme`: String (e.g., "Dark", "Light")
    - `language`: String (e.g., "English", "Spanish")
    - `timezone`: String (e.g., "America/New_York", "America/Los_Angeles")
    - `notifications`: Boolean
    - `notification_sound`: Boolean
    - `notification_sound_data`: String or Binary data
"""

from typing import Optional
from pydantic import BaseModel

class PreferenceBase(BaseModel):
    """Base model for the Preference resource.
    
    Note how _id is not included in the base model.
    This is because _id is generated by the database
    and should not be included when creating a new preference.

    """
    user_id: Optional[str] = None
    theme: Optional[str] = None
    language: Optional[str] = None
    timezone: Optional[str] = None
    notifications: Optional[bool] = None
    notification_sound: Optional[bool] = None
    notification_sound_data: Optional[str] = None

class Preference(PreferenceBase):
    """Model for the Preference resource."""
    _id: str
