"""Path: castor/core/models/screenshot.py

This module contains the Pydantic models for the Screenshot resource.

    - `_id`: ObjectId
    - `project_id`: String (reference to Projects Collection)
    - `task_id`: ObjectId (reference to Tasks Collection)
    - `job_id`: ObjectId (reference to Jobs Collection)
    - `timestamp`: Date
    - `content`: String or Binary data
"""

from datetime import datetime
from typing import Optional
from pydantic import BaseModel

class ScreenshotBase(BaseModel):
    """Base model for the Screenshot resource.
    
    Note how _id is not included in the base model.
    This is because _id is generated by the database
    and should not be included when creating a new screenshot.

    """
    project_id: Optional[str] = None
    task_id: Optional[str] = None
    job_id: Optional[str] = None
    timestamp: Optional[datetime] = None
    content: str

class Screenshot(ScreenshotBase):
    """Model for the Screenshot resource."""
    _id: str
