"""Path: castor/core/models/tag.py

This module contains the Pydantic models for the Tag resource.

    - `_id`: ObjectId
    - `tag_name`: String
    - `tag_description`: String
    - `tag_color`: String (e.g., "#000000", "#FFFFFF")
    - `user_added`: Boolean
    - `user_id`: ObjectId (reference to Users Collection)
"""

from typing import Optional
from pydantic import BaseModel

class TagBase(BaseModel):
    """Base model for the Tag resource.
    
    Note how _id is not included in the base model.
    This is because _id is generated by the database
    and should not be included when creating a new tag.

    """
    tag_name: str
    tag_description: Optional[str] = None
    tag_color: Optional[str] = None
    user_added: Optional[bool] = None
    user_id: Optional[str] = None

class Tag(TagBase):
    """Model for the Tag resource."""
    _id: str
