"""Path: castor/core/models/user.py

This module contains the Pydantic models for the User resource.
    - `_id`: ObjectId
    - `username`: String
    - `email`: String
    - `first_name`: String
    - `last_name`: String
    - `role`: String (e.g., "Admin", "Manager", "User")
    - `projects`: Array of project IDs
    - `profile_picture`: String or Binary data
    - `preferences`: Array of preference documents
"""
from typing import Optional
from pydantic import BaseModel

class UserBase(BaseModel):
    """Base model for the User resource.
    
    Note how _id is not included in the base model.
    This is because _id is generated by the database
    and should not be included when creating a new user.

    """
    username: str
    email: Optional[str] = None
    first_name: str
    last_name: str
    role: Optional[str] = None
    projects: Optional[list] = None
    profile_picture: Optional[str] = None
    preferences: Optional[list] = None

class User(UserBase):
    """Model for the User resource."""
    _id: str
